#!/bin/bash

MOUNT_OPTIONS="-v $(pwd):/pwd"

for arg in "$@"
do
  if (echo $arg | grep -v '/' > /dev/null)
  then
    dname="$arg"
  else
    arg=$(realpath "$arg" 2> /dev/null)
    [ -n "$arg" ] && dname=$(dirname "$arg")
  fi
  if [ -d $dname ]
  then
    MOUNT_OPTIONS="-v $dname:$dname $MOUNT_OPTIONS"
  fi
done

exec docker run \
  --rm \
  -v ~/.config/gcloud:/root/.config/gcloud \
  -v ~/.ssh:/root/.ssh \
  $MOUNT_OPTIONS \
  -e TERM \
  -e USER \
  -w /pwd \
  -it \
  google/cloud-sdk:alpine \
  $*
