#!/bin/bash

MOUNT_OPTIONS="-v $(pwd):/pwd"
NEW_ARGS=

for arg in "$@"
do
  path=$(realpath "$arg" 2> /dev/null)
  if [ -n "$path" ] && (echo $arg | grep '/' > /dev/null)
  then
    NEW_ARGS="$NEW_ARGS $path"
    [ -d "$path" ] || path=$(dirname $path)
    MOUNT_OPTIONS="-v $path:$path $MOUNT_OPTIONS"
  else
    NEW_ARGS="$NEW_ARGS $arg"
  fi
done

exec docker run \
  --rm \
  -v ~/.config/gcloud:/root/.config/gcloud \
  -v ~/.ssh:/root/.ssh \
  $MOUNT_OPTIONS \
  -e TERM \
  -e USER \
  -w /pwd \
  -it \
  google/cloud-sdk:alpine \
  $NEW_ARGS
